# Generated by Django 4.0.2 on 2022-02-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gamerraterapi.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', through='gamerraterapi.GameCategory', to='gamerraterapi.Category'),
        ),
    ]
